In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [24]:
df=pd.read_csv("/content/drive/MyDrive/MLT/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
df.isnull()
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [26]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Cabin'].fillna(df['Cabin'].mode(),inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

df.isnull().sum()

/tmp/ipykernel_10696/2760445575.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)
/tmp/ipykernel_10696/2760445575.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cabin'].fillna(df['Cabin'].mode(),inplace=True)
/tmp/ipykernel_10696/2760445575.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          685
Embarked         0
dtype: int64

In [27]:

from sklearn.preprocessing import LabelEncoder, StandardScaler
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1
2                               Heikkinen, Miss. Laina    0  26.000000      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1
4                             Allen, Mr. William Henry    1  35.000000      0
..                                                 ...  ...        ...    ...
886                              Montvila, Rev. Juozas    1  27.000000      0
887                       Graham, Miss. Margaret Edith    0  19.000000      0
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1
889                              Behr, Mr. Karl Howell    1  26.000000      0
890                                Dooley, Mr. Patrick    1  32.000000      0

     Parch            Ticket     Fare    Cabin  Embarked
0        0         A/5 21171   7.2500  B96 B98         2
1        0          PC 17599  71.2833      C85         0
2        0  STON/O2. 3101282   7.9250       G6         2
3        0            113803  53.1000     C123         2
4        0            373450   8.0500      NaN         2
..     ...               ...      ...      ...       ...
886      0            211536  13.0000      NaN         2
887      0            112053  30.0000      B42         2
888      2        W./C. 6607  23.4500      NaN         2
889      0            111369  30.0000     C148         0
890      0            370376   7.7500      NaN         1

[891 rows x 12 columns]

In [28]:
x = df[['Pclass', 'Sex', 'Age', 'Fare']]
y = df['Survived']

In [29]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train , y_test= train_test_split(x, y,
    test_size=0.2, random_state=1
)

In [30]:
from sklearn.neighbors import KNeighborsClassifier
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# KNN Model
model = KNeighborsClassifier(n_neighbors=5)

# Train model
model.fit(x_train, y_train)

# Prediction
y_pred = model.predict(x_test)

In [31]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7541899441340782